<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [ ]:
x = 0
x -= 1
assert x >= 0, 'x is becoming negative!'
print(x)

In [ ]:
x = 0
x += 1
assert x >= 0, 'x is becoming negative!'
print(x)

### 1.2 try-except

In [ ]:
# To handle exceptions (things that go wrong)

try: # to enclose part of the code that may get into trouble
    
    number = input()

    square = int(number)**2

    print(f'The square of {number} is {square}!')
    
except: # if something goes wrong, code under try will be ignored, and this will be run instead 
    print(f'{number} is not a number')

## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [ ]:
def funny_ADD(A, B, C=1): 
    return A + B*10 + 100*C 

funny_ADD(1,2) # two positional, 1 default
# 1 + 2(10) + 1(100)

In [ ]:
def funny_ADD(A, B, C=1): 
    return A + B*10 + 100*C 

funny_ADD(1,2, 3) # three positional, default is overridden
# 1 + 2(10) + 3(100)

In [ ]:
def funny_ADD(A, B, C=1): 
    return A + B*10 + 100*C 

funny_ADD(A=1, B=3) # two keyword, 1 default
# not positional, as the variables have been defined
# 1 + 3(10) + 1(100)

In [ ]:
def funny_ADD(A, B, C=1): 
    return A + B*10 + 100*C 

funny_ADD(A=1, B=3, C=5) # three keyword (arrangement does not matter)
# 1 + 3(10) + 5(100)

In [ ]:
def funny_ADD(A, B, C=1): 
    return A + B*10 + 100*C 

funny_ADD(1, B=3, C=5) # one positional, 2 keywords
# 1 + 3(10) + 5(100)

In [ ]:
def funny_ADD(A, B, C=1): 
    return A + B*10 + 100*C 

funny_ADD(1, B=3, C=5) # one positional, 2 keywords
# 1 + 3(10) + 5(100)

In [ ]:
def funny_ADD(A, B, C=1): 
    return A + B*10 + 100*C 

funny_ADD(1, B=3) # one positional, 1 keyword, 1 default
# 1 + 3(10) + 1(100)

In [ ]:
def funny_ADD(A, B, C=1): 
    return A + B*10 + 100*C 

funny_ADD(1, B=3, 5) # 1 positional, 1 keyword, 1 positional
# 1 + 3(10) + 5(100)

# !positional argument cannot follow keyword argument

# Python cannot figure out the position of the final data

### 2.2 Docstrings

In [ ]:
# to document what a fucntion does inide a function
# before specifiying output when defining function
# stays in between 2 pairs of ''' or """

def funny_ADD(A, B, C=1):
    '''
    A test function to demo how positional, keyword
    abd default arguments work
    '''
    
    return A + B*10 + 100*C 

help(funny_ADD) # notice fucntion name is within the 
                # help() fucntion's brackets

### 2.3 Function are first class citizens

In [ ]:
import numpy as np

In [ ]:
# pass a fucntion as an argument to another function

def my_func(angle, trig_function):
    return trig_function(angle)

# Let's use the function
print(my_func(np.pi/2, np.sin))

print(my_func(np.pi/2, np.cos))

print(my_func(np.pi/2,np.tan))

my_func(np.pi/2, lambda x: np.cos(2*x)) # WTF is happening here

### 2.4 More unpacking -> can extract info from lists

In [ ]:
x, y, z = [1, 2, 3]
print(x, y, z)


In [ ]:
x, y, z = np.array([1, 2, 3])
print(x, y, z)

In [ ]:
x, *y, z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

# I'm guessing y takes everything in-between?

In [ ]:
x, *_, z = np.array([1, 2, 3, 4, 5])
print(x, z)

# I'm guessing everything in-between the first element
# [index 0] and the last element [index -1] is voided?

## Exercise 1 :  A better calculator I

In [ ]:
# Exactly what Exercise 1 wants (part 1)

def add(x,y):
    return x + y

def subtract (x,y):
    return x - y

def multiply(x,y):
    return x*y

def divide(x,y):
    assert y != 0, 'oh no!'
    return int(x/y)

print(add(5,4))
print(subtract(9,3))
print(multiply(7,4))
print(divide(8,1))

print(divide(9,0))
print(divide(0,9))




In [ ]:
import numpy as np

In [ ]:
# Exactly what Exercise 1 wants (part 2)

def add(x,y):
    return x + y

def subtract (x,y):
    return x - y

def multiply(x,y):
    return x*y

def divide(x,y):
    assert y.any() != 0, 'oh no!'
    return (x/y)

x = np.array([36, 34, 44, 76, 77])
y = np.array([64, 66, 56, 24, 73])

print(add(x,y))
print(subtract(x,y))
print(multiply(x,y))
print(divide(x,y))

## Exercise 2 :  A better calculator II

In [1]:
# Exactly what Exercise 2 wants (part 1)

def add(x,y):
    return x + y

def subtract (x,y):
    return x - y

def multiply(x,y):
    return x*y

def divide(x,y):
    assert y != 0, 'oh no!'
    return (x/y)

print(add(5,4))
print(subtract(9,3))
print(multiply(7,4))
print(divide(8,1))

print(divide(9,0))

9
6
28
8.0


AssertionError: oh no!

In [4]:
import numpy as np

In [6]:
# Exactly what Exercise 2 wants (part 2)

x = np.array([36, 34, 44, 76, 77])
y = np.array([64, 66, 56, 24, 73])

def add(x,y):
    return x + y

def subtract (x,y):
    return x - y

def multiply(x,y):
    return x*y

def divide(x,y):
    try:
        return (x/y)
    except: # No need to put what criteria has to 
            # be met for code to not work
            # Just if ANYTHING GOES WRONG, end up here
        return 'oh no!'


print(add(x,y))
print(subtract(x,y))
print(multiply(x,y))
print(divide(x,y))




[100 100 100 100 150]
[-28 -32 -12  52   4]
[2304 2244 2464 1824 5621]
[0.5625     0.51515152 0.78571429 3.16666667 1.05479452]


In [12]:
# Exactly what Exercise 2 wants (part 3)

x = np.array([36, 34, 44, 76, 77])
y = np.array([64, 66, 56, , 73])

def add(x,y):
    return x + y

def subtract (x,y):
    return x - y

def multiply(x,y):
    return x*y

def divide(x,y):
    try:
        return (x/y)
    except ZeroDivisionError:
        return 'oh no!'


print(add(x,y))

print(subtract(x,y))

print(multiply(x,y))

print(divide(x,y))




[100 100 100 100 150]
[-28 -32 -12  52   4]
[2304 2244 2464 1824 5621]
[0.5625     0.51515152 0.78571429 3.16666667 1.05479452]


In [3]:
import numpy as np

In [9]:
y = np.array([10, 66, 56, 24, 73])
(y > 20).all() # asking if all of the elements within are more than 20


False

In [10]:
y = np.array([10, 66, 56, 24, 73])
(y > 20).any() # asking if any of the elements within are more than 20


True

In [16]:
y = np.array([0, 66, 56, 24, 73])
(y == 0).any() # asking if any of the elements within are more than 20


True

In [23]:
a = np.array([36, 34, 44, 76, 77])
b = np.array([0, 66, 56, 24, 73]) # array that has an element with
                                # value of 0

def add(x,y):
    return x + y

def subtract (x,y):
    return x - y

def multiply(x,y):
    return x*y

def divide(x,y):
    try:
        return (x/y)
        assert (y == 0).any()
    except:
        return 'oh no!'


print(add(a,b))
print(subtract(a,b))
print(multiply(a,b))
print(divide(a,b))




[ 36 100 100 100 150]
[ 36 -32 -12  52   4]
[   0 2244 2464 1824 5621]
[       inf 0.51515152 0.78571429 3.16666667 1.05479452]


C:\Users\ASUS\AppData\Local\Temp\ipykernel_20460\401799458.py:16: RuntimeWarning: divide by zero encountered in divide
  return (x/y)


In [2]:
import numpy as np

In [4]:
a = np.array([36, 34, 44, 76, 77])
b = np.array([0, 66, 56, 10, 73]) # array that has an element with
                                # value of 0
#import warnings
#warnings.filterwarnings('error')

def add(x,y):
    return x + y

def subtract (x,y):
    return x - y

def multiply(x,y):
    return x*y

def divide(x,y):
    try:
        assert y.any() == 0 
        return (x/y)
    except:
        return 'oh no!, >= 1 element in y is 0'


print(add(a,b))

print(subtract(a,b))

print(multiply(a,b))

print(divide(a,b))




[ 36 100 100  86 150]
[ 36 -32 -12  66   4]
[   0 2244 2464  760 5621]
oh no!, >= 1 element in y is 0


In [14]:
my_list = [0,1,2]
my_array = np.array(my_list)
my_array.all(0)

False

In [17]:
my_list = [0]
my_array = np.array(my_list)
my_array.all(0)

False

In [18]:
my_list = [0,1,2]
my_array = np.array(my_list)
my_array.any()

True