<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [3]:
def hello(name):
    if name == 'Capy':
        return 'Ok I pull up'
    else:
        return 'no pull up :('

hello('Capy')

'Ok I pull up'

In [4]:
def hello(name):
    if name == 'Capy':
        return 'Ok I pull up'
    else:
        return 'no pull up :('

hello('Cap')

'no pull up :('

In [8]:
name = input('name:')

def hello(name):
    if name == 'Capy':
        return 'Ok I pull up'
    else:
        return 'no pull up :('

hello(name) # use variable name inside the brackets instead

name:Capy


'Ok I pull up'

In [10]:
name = input('name:')

def hello(name):
    if name == 'Capy':
        return 'Ok I pull up'
    else:
        return 'no pull up :('

hello('Capy')

# does not care about user input

name:go


'Ok I pull up'

In [11]:
name = input('name:')

def hello(name):
    if name == 'Capy':
        return 'Ok I pull up'
    else:
        return f'dammit {name}'

hello(name)

# does not care about user input

# return just tells function to give me this - whatever
# is after return

name:bubbles


'dammit bubbles'

When Python sees a `return` keyword its jumps out of the function with the return value

In [4]:
def hello(name):
    if name == 'Capy':
        return 'Ok I pull up'
    else:
        return 'no pull up :('

hello('Cap')

'no pull up :('

In [13]:
# Pick up returned value by assigning it to a variable

greet = hello(name = 'Superman')
print(greet)



dammit Superman


In [16]:
# Use returned value directly

print(hello(name = 'Capy'))

Ok I pull up


In [17]:
import numpy as np

In [27]:
def basic_stats(numbers):
    np_numbers = np.array(numbers)
    return np.array([np_numbers.min(), np_numbers.max(), np_numbers.mean()])

array_min, array_max, array_mean = basic_stats([1, 2, 3, 4, 5])


In [28]:
basic_stats([1, 2, 3, 4, 5])

# Unpacking 

array([1., 5., 3.])

In [27]:
def basic_stats(numbers):
    np_numbers = np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])


In [34]:
[list_min, list_max, list_mean] # square brackest around 
# makes a list

[1, 5, 3.0]

In [30]:
basic_stats([1, 2, 3, 4, 5]) # gives an array

array([1., 5., 3.])

In [33]:
def basic_stats(ank):
    np_ank = np.array(ank)
    return np_ank.min(), np_ank.max(), np_ank.mean()

list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])

list_min, list_max, list_mean # 3 variables 

(1, 5, 3.0)

### 1.2 Named functions that don’t return

In [ ]:
# some functions do not return a value
# no value returned



**REQUIRED FOR WHEN SAVING A FILE**

### 1.3 Anonymous functions

In [37]:
my_short_function = lambda name: f'Hello {name}'
my_short_function(name = 'capy')

# lambda fucntion returns value of last statement

'Hello capy'

In [38]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)      

# first element of the sub-list is what the sorting is based on

# The default key is compared 
# Just happened to have this order
# Sorting the 3 elements 

# Done in ascending order

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [39]:
numbers=[[9, 0, 10],
         [9, 1, 11],
         [9, 2, 12],
         [9, 3, 13],
         [9, 4, 14],
         [9, 5, 15],
         [9, 6, 16],
         [9, 7, 17],
         [9, 8, 18],
         [9, 9, 19]]

sorted(numbers)      

# The default key is compared 


[[9, 0, 10],
 [9, 1, 11],
 [9, 2, 12],
 [9, 3, 13],
 [9, 4, 14],
 [9, 5, 15],
 [9, 6, 16],
 [9, 7, 17],
 [9, 8, 18],
 [9, 9, 19]]

In [2]:
# specify a key for use of comparison

numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]


sorted(numbers, key = lambda x: x[1])

# sort by comparing a custom key
# that uses the 2nd element

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [3]:
# specify a key for use of comparison

numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]


sorted(numbers, key = lambda x: x[2])

# sort by comparing a custom key
# that uses the 3rd element

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [4]:
# specify a key for use of comparison

numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]


sorted(numbers, key = lambda x: sum(x))

# sort by comparing a custom key
# that uses the sum of the elements in each sublist
# all done in ascending order

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [7]:
# specify a key for use of comparison
# HELP

numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]


sorted(numbers, key = lambda x: max(x))

# sort by comparing a custom key
# that uses the sum of the elements in each sublist
# all done in ascending order

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [6]:
# specify a key for use of comparison

numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]


sorted(numbers, key = lambda x: min(x))

# sort by comparing a custom key
# that uses the sum of the elements in each sublist
# all done in ascending order

[[9, 0, 10],
 [0, 9, 19],
 [8, 1, 11],
 [1, 8, 18],
 [7, 2, 12],
 [2, 7, 17],
 [6, 3, 13],
 [3, 6, 16],
 [5, 4, 14],
 [4, 5, 15]]

### 1.4 Optional arguments

make arguments to our function optional!!


In [16]:
def hello(name='no one'): # argument with default value
                            # it always has something to work with
    if name == 'Batman':
        return 'Hello Batman! So nice to meet you!'
    else:
        return f'Hello {name} !'
    
hello()

'Hello no one !'

In [20]:
def hello(name = 'no one'): # argument with default value
                            # it always has something to work with
    if name == 'Batman':
        return 'Hello Batman! So nice to meet you!'
    else:
        return f'Hello {name} !'
    
hello() # returning what was originally placed in
# fucntion working without an argument

'Hello no one !'

In [22]:
def hello(name): 
    
    if name == 'Batman':
        return 'Hello Batman! So nice to meet you!'
    else:
        return f'Hello {name} !'
    
hello('name') # returning what is now placed in

'Hello name !'

In [25]:
print('i','am','batman!') # spearated by space

print('i','am','batman',sep = '---') # separated by 3 lines

i am batman!
i---am---batman


In [24]:
print('i''am''batman!')

iambatman!


## 2 The importance of functions?

### 2.1 An argument for functions

In [ ]:

# Your code here


### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

An else statement is not required here as the second *return* key is indented at the same indent as the *if* statment (that specifies its own condtion).
The value following the second *return* key will provide its return value if the condition specified by the *if* statement is not met

In [29]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

greeting('Batman')




'Hello Batman! So, nice to meet you!'

In [30]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

greeting('Spiderman')




'Hello Spiderman!'

In [31]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    elif name == 'Superman':
        return 'Look its Superman!'
    return f'Hello {name}!'

greeting('Superman')




'Look its Superman!'

In [32]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    elif name == 'Superman':
        return 'Look its Superman!'
    return f'Hello {name}!'

greeting('Spiderman')




'Hello Spiderman!'

## Exercise 2 :  Calculator functions

In [3]:
# Exactly what Exercise 2 wants (part 1)

def add(x,y):
    return x + y

def subtract (x,y):
    return x - y

def multiply(x,y):
    return x*y

def divide(x,y):
    if (y == 0):
        exit() # Python stops
    else:
        return int(x/y)

print(add(5,4))
print(subtract(9,3))
print(multiply(7,4))
print(divide(8,1))

print(divide(9,0))
print(divide(0,9))

# return means 'give me back this value'
# so use that instead of print()

9
6
28
8
None
0


In [12]:
# Exactly what Exercise 2 wants (part 2)

def add(x,y):
    return x + y

def subtract (x,y):
    return x - y

def multiply(x,y):
    return x*y

def divide(x,y):
    if y.any() == 0:
        exit()
    else:
        return x/y

x = np.array([36, 34, 44, 76, 77])
y = np.array([64, 66, 56, 24, 73])

print(add(x,y))
print(subtract(x,y))
print(multiply(x,y))
print(divide(x,y))


[100 100 100 100 150]
[-28 -32 -12  52   4]
[2304 2244 2464 1824 5621]
[0.5625     0.51515152 0.78571429 3.16666667 1.05479452]


In [2]:
def add(x,y):
    return x + y

def subtract (x,y):
    return x - y

def multiply(x,y):
    return x*y

def divide(x,y):
    if (y == 0) :
        return 'oh no!'
    else:
        return int(x/y)

print(add(5,4))
print(subtract(9,3))
print(multiply(7,4))
print(divide(8,1))

print(divide(9,0))
print(divide(0,9))

# return means 'give me back this value'
# so use that instead of print()
# no Nonetype data appears because I used return

9
6
28
8
oh no!
0


In [1]:
def add(x,y):
    return x + y

def subtract (x,y):
    return x - y

def multiply(x,y):
    return x*y

def divide(x,y):
    if (y == 0) :
        print('oh no!')
    else:
        return int(x/y)

print(add(5,4))
print(subtract(9,3))
print(multiply(7,4))
print(divide(8,1))

print(divide(9,0))
print(divide(0,9))

# return means 'give me back this value'
# so use that instead of print()
# because print() is used here, the line after is Nonetype data

9
6
28
8
oh no!
None
0


In [7]:
def add(x,y):
    return x + y

def subtract (x,y):
    return x - y

def multiply(x,y):
    return x*y

def divide(x,y):
    assert (x > 0 or y > 0), 'indivisible by 0!'
    return int(x/y)

print(add(5,4))
print(subtract(9,3))
print(multiply(7,4))
print(divide(8,1))

print(divide(9,0))
print(divide(0,9))

9
6
28
8


ZeroDivisionError: division by zero

In [2]:
import numpy as np

## Exercise 3 :  max_info() with NumPy

In [9]:
# Exactly what Exercise 3 wants

def max_info(numbers):
    return np.max(numbers), np.argmax(numbers)
# element with the maximum value within the list and 
# index of that element to show up as output

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]
# numbers = np.array(numbers)


x, y = max_info(numbers)
print(x)
print(y)

83
2


In [21]:
def max_info(numbers):
    return [numbers.max(), numbers.argmax()] # array
# element with the maximum value within the list and 
# index of that element to show up as output

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]
numbers = np.array(numbers)
max_info(numbers)



[83, 2]

In [2]:
import numpy as np

In [7]:
def max_info(numbers):
    return numbers.max(), numbers.argmax() # tuple
# element with the maximum value within the list and 
# index of that element to show up as output

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]
numbers = np.array(numbers)


x,_ = max_info(numbers) # if you don't care about naming\

x

83

In [18]:
def max_info(numbers):
    return numbers.max() 
    return numbers.argmax()

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]
numbers = np.array(numbers)

max_info(numbers)


83