<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

##### ***3 BASIC WAYS OF STORING DATA

In [ ]:

# python lists

py_superhero_names = ['Batman', 'Iron Man', 'Doctor Strange']
py_real_names = ['Bruce Wayne', 'Tony Stark', 'Stephen Strange']


In [ ]:

# python array (Numpy Arrays)

py_superhero_names = np.array(['Batman', 'Iron Man', 'Doctor Strange'])
py_real_names = np.array(['Bruce Wayne', 'Tony Stark', 'Stephen Strange'])


In [ ]:

# python array (Dictionaries)

superhero_info = {'Bruce Wayne': 'Batman', 'Tony Stark': 'Iron Man', 'Stephen Strange': 'Doctor Strange'}


### 1.2 Accessing data from a list (or array)

In [3]:

py_superhero_names = ['Batman', 'Iron Man', 'Doctor Strange']
print(py_superhero_names[2]) # means THIRD in the list, REMEMBER FIRST VARIABLE IS NUMBERED AS 0

print(py_superhero_names[-1]) # means first from the end

print(py_superhero_names[-2])

Doctor Strange
Doctor Strange
Iron Man


### 1.3 Accessing data from a dictionary

In [6]:

superhero_info = {'Tim Drake': 'Red Robin', 'Dick Grayson': 'Nightwing', 'Barbara Gordon': 'Batgirl'}

print(superhero_info['Red Robin'])

#Placement of key and value matters!!!

KeyError: 'Red Robin'

In [1]:

superhero_real_identity = {'Red Robin': 'Tim Drake', 'Nightwing': 'Dick Grayson', 'Batgirl': 'Barabara Gordon'}

print(superhero_real_identity['Red Robin'])

# HOW TO MAKE THIS WORK
# ONE AT A TIME 

Tim Drake


In [2]:

superhero_real_identity = {'Red Robin': 'Tim Drake', 'Nightwing': 'Dick Grayson', 'Batgirl': 'Barabara Gordon'}

print(superhero_real_identity['Nightwing'])

# HOW TO MAKE THIS WORK
# ONE AT A TIME 

Dick Grayson


In [1]:

superhero_real_identity = {'Red Robin': 'Tim Drake', 'Nightwing': 'Dick Grayson', 'Batgirl': 'Barabara Gordon'}

print(superhero_real_identity['Red Robin'])

print(superhero_real_identity.keys())

superhero_real_identity.values() # OUTPUT IS ONLY LAST LINE OF CODE SO THIS IS NOT EXECUTED

# WILL ONLY GIVE ME ONE AT A TIME? YES MUST CALL PRINT FUNCTION FOR
# ANYTHING BEFORE LAST LINE OF CODE BLOCK

Tim Drake
dict_keys(['Red Robin', 'Nightwing', 'Batgirl'])


dict_values(['Tim Drake', 'Dick Grayson', 'Barabara Gordon'])

In [13]:

superhero_real_identity = {'Red Robin': 'Tim Drake', 'Nightwing': 'Dick Grayson', 'Batgirl': 'Barabara Gordon'}

print(superhero_real_identity['Red Robin'])

superhero_real_identity.keys()



Tim Drake


dict_keys(['Red Robin', 'Nightwing', 'Batgirl'])

### 1.4 Higher dimensional lists

In [16]:
#WHATS THE POINT OF THIS 

superhero_real_identity = [['Red Robin', 'Tim Drake'], ['Nightwing', 'Dick Grayson'], ['Batgirl', 'Barabara Gordon']]
superhero_real_identity.values()

#STORE CORRESPONDING REAL AND SUPERHERO NAMES AS A 2D LIST

AttributeError: 'list' object has no attribute 'values'

## 2 Lists vs. Arrays

### 2.1 Size

In [19]:
import numpy as np

In [4]:

py_list_nama_saya_aakash = [[1,'A'],[2,'A'],[3,'K'],[4,'A'],[5,'S'],[6,'H']]


#To recreate the Python list to create a NEW NumPy array



len(py_list_nama_saya_aakash)



6

In [2]:
import numpy as np
py_list_nama_saya_aakash = [[1,'A'],[2,'A'],[3,'K'],[4,'A'],[5,'S'],[6,'H']]


#To recreate the Python list to create a NEW NumPy array

np_array_nama_saya_aakash = np.array(py_list_nama_saya_aakash)



len(np_array_nama_saya_aakash)




6

In [24]:

py_list_nama_saya_aakash = [[1,'A'],[2,'A'],[3,'K'],[4,'A'],[5,'S'],[6,'H']]


#To recreate the Python list to create a NEW NumPy array

np_array_nama_saya_aakash = np.array(py_list_nama_saya_aakash)



len(np_array_nama_saya_aakash)

np_array_nama_saya_aakash.shape

(6, 2)

### 2.2 Arrays are fussy about type

In [25]:
py_list = [2,2.0,'A']
np.array(py_list)

# NumPy arrays tolerate ONE TYPE a single time
# Lists don't  care how many data types you have

array(['2', '2.0', 'A'], dtype='<U32')

### 2.3 Adding a number

In [26]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

#Reusing the python list to create a NEW NumPy array

py_list + 10

TypeError: can only concatenate list (not "int") to list

In [6]:
import numpy as np

py_list = [1, 2, 3, 4, 5.0]
np_array = np.array(py_list)
#Reusing the python list to create a NEW NumPy array

#So all made to int type? Everything is float type 
np_array2 = np_array + 10

type(np_array2[0]) #This is how to check

numpy.float64

NameError: name 'np_array' is not defined

In [ ]:
py_list 


### 2.4 Adding another list

In [29]:
py_list_1 = [1,2,3,4]

py_list_2 = [10,20,30,40]

py_list_1 + py_list_2

# adding lists, placing them side-by-side

[1, 2, 3, 4, 10, 20, 30, 40]

In [33]:
py_list_1 = [1,2,3,4]

py_list_2 = [10,20,30,40]



np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

np_array_1 + np_array_2

# adding arrays together

array([11, 22, 33, 44])

### 2.5 Multiplying by a Number

In [41]:
py_list_1 = [1,2,3,4]

py_list_2 = [10,20,30,40]

py_list_1*2


# multiplying lists to make more of the same list

[1, 2, 3, 4, 1, 2, 3, 4]

In [40]:
py_list_1 = [1,2,3,4]

py_list_2 = [10,20,30,40]


py_list_2*2

# multiplying lists to make more of the same list 
#CANNOT MULTIPLY DATA IN LISTS BY 2? NO, EXPLANATION BELOW

[10, 20, 30, 40, 10, 20, 30, 40]

In [8]:
py_list_1 = [1,2,3,4]

py_list_2 = [10,20,30,40]

np_array1 = np.array(py_list_1)
np_array1*2

# multiplying lists to make more of the same list 
#CANNOT MULTIPLY DATA IN LISTS BY 2?
#MUST MAKE INTO ARRAY FOR THIS 
#ARRAY SUPERIORITY - FOR multiplication of all values in here
# ONLY LIST CAN BE MULTIPLIED TWICE

array([2, 4, 6, 8])

In [42]:
py_list_1 = [1,2,3,4]

py_list_2 = [10,20,30,40]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

np_array_1 * 2

# multiplying arrays BY A NUMBER

array([2, 4, 6, 8])

In [43]:
py_list_1 = [1,2,3,4]

py_list_2 = [10,20,30,40]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

np_array_2 * 2

# multiplying arrays BY A NUMBER

array([20, 40, 60, 80])

In [35]:
py_list_1 = [1,2,3,4]

py_list_2 = [10,20,30,40]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

np_array_1 * np_array_2

# multiplying arrays together

array([ 10,  40,  90, 160])

In [ ]:

# Your code here


### 2.6 Squaring

In [45]:
py_list_1 = [1,2,3,4]
np_array = np.array(py_list_1)

np_array**2

array([ 1,  4,  9, 16])

### 2.7 Asking questions

In [2]:
import numpy as np

In [3]:
py_list_1 = [1,2,3,4]
np_array = np.array(py_list_1)

py_list_1 == 3

# py_list_2 = [3]
# py_list_2 == 3

False

In [4]:
py_list_2 = [3]
py_list_2 == 3

False

In [9]:
py_list_1 = [1,2,3,4]
np_array = np.array(py_list_1)

py_list_1 == 3

py_list_2 = [3]
np_array > 3 #MORE THAN


array([False, False, False,  True])

In [12]:
py_list_1 = [1,2,3,4]
np_array = np.array(py_list_1)

py_list_1 == 3

py_list_2 = [3]
np_array >= 3 #MORE THAN OR EQUALS TO


array([False, False,  True,  True])

In [10]:
py_list_1 = [1,2,3,4]
np_array = np.array(py_list_1)

py_list_1 == 3

py_list_2 = [3]
np_array <= 3 #LESS THAN OR EQUALS TO


array([ True,  True,  True, False])

In [11]:
py_list_1 = [1,2,3,4]
np_array = np.array(py_list_1)

py_list_1 == 3

py_list_2 = [3]
np_array != 3 #NOT EQUALS TO


array([ True,  True, False,  True])

In [50]:
import numpy as np

In [55]:
py_list_1 = [1,2,3,4]
np_array = np.array(py_list_1)

np_array == 3

array([False, False,  True, False])

In [54]:
py_list_1 = [1,2,3,4]
np_array = np.array(py_list_1)

np_array > 3

array([False, False, False,  True])

In [ ]:

# Your code here


### 2.8 Mathematics

In [57]:

py_list = [1,2,3,4]
np_array = np.array(py_list)

sum(py_list) #ADD THE DATA IN THE LIST TOGETHER

10

In [58]:

py_list = [1,2,3,4]
np_array = np.array(py_list)

max(py_list) # FIND LARGEST VALUE DATA IN LIST

4

In [58]:

py_list = [1,2,3,4]
np_array = np.array(py_list)

min(py_list) # FIND SMALLEST VALUE DATA IN LIST

4

In [59]:

py_list = [1,2,3,4]
np_array = np.array(py_list)

np_array.min() # FIND SMALLEST VALUE DATA IN ARRAY

1

In [60]:

py_list = [1,2,3,4]
np_array = np.array(py_list)

np_array.max() # FIND LARGEST VALUE DATA IN ARRAY

4

In [15]:

py_list = [1,2,3,4]
np_array = np.array(py_list)

np_array.sum() #FIND SUM OF ALL VALUE DATA IN ARRAY

10

In [16]:

py_list = [1,2,3,4]
np_array = np.array(py_list)

np_array.sum() #FIND SUM OF ALL VALUE DATA IN ARRAY

list(np_array) # convert array back into list

[1, 2, 3, 4]

## Exercise 1 :  Total recall?




***2 SIMILARITIES BETWEEN LISTS AND ARRAYS***

1. Lists and arrays can be interconverted to one-another - 
- function to convert list to array -> **new array name** = np.array(**insert list name**)
- function to convert array to list -> **new list name** = list(**insert array name**)
    
1. len function can be used on them to tell how many values are in them. - len(**insert list/array name**). 
    
***2 DIFFERENCES BETWEEN LISTS AND ARRAYS***
    
1. NumPy Array can only store a single type of data at once - e.g. np_array = [1,'dua',3.0] will all be stored as strings (shown in output). Python lists can store integer, float, string type data.

1. shape - a property/attribute *(NOT A FUNCTION)* of NumPy arrays can be used on arrays but not lists - output is as follows, (no. that tells how many data sets there are, no. that tells how many lists are stored in the array) - applicable for when there are $$ \geq 2 $$ lists stored in that 1 array. *Might be applicable for the array superiority over the dictionary (higher dimensional dictionaries). When the corresponding data of the keys and values of the dictionary are in 2 separate lists.*

***MORE DIFFERENCES BETWEEN LISTS AND ARRAYS BY CLEMENT***
1. Lists use mpre memory than arrays because each element in a list is an object, while arrrays store elements in a more efficient manner. 

1. Hence, lists are slower when it comes to numerical computation.

1. Lists are native to Python, while arrays are part of the NumPy library.

***What is a dictionary***
A dictionary is a data storing function *NOT FUNCTION - it is a strategy* that has keys which are tagged to *their associated* values. Looks like *dictionary name* = { '**key**' : '**value**' , '**key**' : '**value**'} - colon : 

## Exercise 2 :  Index me

In [5]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]

# Prints 'a1'
print(py_list[0]) 

# Prints 'c3'
print(py_list[2])

# Prints 'e5'
print(py_list[4]) 
                   
# Prints 'g7'
print(py_list[-4])      

# Prints 'i9'
print(py_list[-2]) 

a1
c3
e5
g7
i9


In [1]:
import numpy as np

In [11]:
# Code to present all the elements withh an odd number in
# a single list

py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]

py_array = np.array(py_list)

list(py_array[0:100:2])

['a1', 'c3', 'e5', 'g7', 'i9']

In [41]:
# Code to present all the elements withh an odd number in
# a single list

# Familiarise yourself with what lists and arrays can do!!!!

py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]

py_list[0:100:2]

    # familiarise yourself with what arrays and lists each are 
    # capable of, so you don't have to keep converting
    # from one to another

['a1', 'c3', 'e5', 'g7', 'i9']

## Exercise 3 :  Capitalise Heros

In [14]:
superhero_info = {'Natasha Romanoff': 'Black Widow',
                  'Tony Stark': 'Iron Man',
                  'Stephen Strange': 'Doctor Strange'
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()                  
print(superhero_info['Tony Stark'])


IRON MAN


In [17]:
superhero_info = {'Natasha Romanoff': 'Black Widow',
                  'Tony Stark': 'Iron Man',
                  'Stephen Strange': 'Doctor Strange'
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()                  
print(superhero_info['Tony Stark'])

superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
print(superhero_info['Natasha Romanoff'])

superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()
print(superhero_info['Stephen Strange'])



IRON MAN
BLACK WIDOW
DOCTOR STRANGE


In [40]:
superhero_info = {'Natasha Romanoff': 'Black Widow',
                  'Tony Stark': 'Iron Man',
                  'Stephen Strange': 'Doctor Strange'
                  }

for key, value in superhero_info.items():
    print({value}.upper())



AttributeError: 'set' object has no attribute 'upper'

In [39]:
superhero_info = {'Natasha Romanoff': 'Black Widow',
                  'Tony Stark': 'Iron Man',
                  'Stephen Strange': 'Doctor Strange'
                  }

for key, value in superhero_info.items():
    print(f'{key.upper()} is {value.upper()}!')

    # items() will get both key and value 
    # only need value here

NATASHA ROMANOFF is BLACK WIDOW!
TONY STARK is IRON MAN!
STEPHEN STRANGE is DOCTOR STRANGE!


In [33]:
superhero_info = {'Natasha Romanoff': 'Black Widow',
                  'Tony Stark': 'Iron Man',
                  'Stephen Strange': 'Doctor Strange'
                  }

for key in superhero_info.keys():
    value = superhero_info[key]
    print(value.upper())

# only need value here
# note to future Aakash from past Aakash: 
# be familiar with .keys() and .items() for dictionaries 
# - latter gives both key and value former only gives value

when want to use hidden function within an f-string, {<variable name>.upper()}

BLACK WIDOW
IRON MAN
DOCTOR STRANGE


In [3]:
superhero_info = {'Natasha Romanoff': 'Black Widow',
                  'Tony Stark': 'Iron Man',
                  'Stephen Strange': 'Doctor Strange'
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()                  
print(superhero_info['Tony Stark'])

superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
print(superhero_info['Natasha Romanoff'])

superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()
print(superhero_info['Stephen Strange'])

print(superhero_info.capitalise())

# uppercase the value by indexing the key, cannot capitalised entire dictionary

IRON MAN
BLACK WIDOW
DOCTOR STRANGE


AttributeError: 'dict' object has no attribute 'capitalise'

In [42]:
superhero_info = {'Natasha Romanoff': 'Black Widow',
                  'Tony Stark': 'Iron Man',
                  'Stephen Strange': 'Doctor Strange'
                  }

superhero_info['Natasha Romanoff','Tony Stark'] = superhero_info['Tony Stark'].upper()                  
print(superhero_info['Tony Stark'])

print(superhero_info[0])

Iron Man


KeyError: 0

## Exercise 4 :  How many ones

In [2]:
import numpy as np # Can be placed outside 

In [3]:
numbers_list = [45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
                99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
                83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
                1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
                8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  


new_array = np.array(numbers_list)

new_array == 1 # Asking this question gives an array itself as an output

array([False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False])

In [6]:
# import numpy as np

numbers_list = [45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
                99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
                83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
                1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
                8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  


new_array = np.array(numbers_list)

newest_array = new_array == 1

newest_array.sum() # Newest array summing up all the True values that are 1

9

In [7]:
numbers_list = [45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
                99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
                83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
                1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
                8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  


new_array = np.array(numbers_list)
(new_array == 1).sum() # faster way to code after asking question, without making an entirely new array

9