<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [1]:
import numpy as np

In [2]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one

x = np_array

x[0] # Element with first index (0th place)


'a1'

In [3]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one

x = np_array

x[-1] # Element with the last index


'j10'

In [4]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR


x[0:-1] # element with first index to element with last index


['a1', 'b2', 'c3', 'd4', 'e5', 'f6', 'g7', 'h8', 'i9']

In [5]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one

x = np_array

x[0:2] # Element with first index to element with second index only!
# Element with third index (at second place) is not given as output


array(['a1', 'b2'], dtype='<U3')

In [6]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR


x[0:-1:3] # First element to second element only!
# Third element at place 2 is not given as output


['a1', 'd4', 'g7']

In [7]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one

x = np_array

x[0:0:3] # First element to first element 


array([], dtype='<U3')

In [8]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR


x[1:10:2] # First element to last in steps of 2
# Elements with even number indexes show up


['b2', 'd4', 'f6', 'h8', 'j10']

In [9]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one

x = np_array

x[0:10:2] # First element to last in steps of 2,
# Elements with odd number indexes show up


array(['a1', 'c3', 'e5', 'g7', 'i9'], dtype='<U3')

In [10]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  

x[5:2:-1] # Element with 5th index to element to element with 
# 2nd index (in reverse - as stated by the -1)  


['f6', 'e5', 'd4']

In [11]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one

x = np_array

x[5:2:1] # Element with 5th index to element to element with 
# 2nd index (CANNOT GO FORWARED WHEN IT IS IN PLACES OF 1)  


array([], dtype='<U3')

In [12]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR


x[::1] # Element with first index to element with last index 
# in steps of 1


['a1', 'b2', 'c3', 'd4', 'e5', 'f6', 'g7', 'h8', 'i9', 'j10']

In [13]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one

x = np_array

x[::3] # Element with first index to element with last index 
# in steps of 3
# , means within the list that is an element of the major list
# value that follows is the index of the list within


array(['a1', 'd4', 'g7', 'j10'], dtype='<U3')

### 1.2 Subsetting by masking (Arrays only)

In [14]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask) 
# CAN ONLY BE DONE WITH NumPy arrays!!

[False False False  True  True  True  True  True  True  True]


In [15]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 9
print(my_mask)
# Only last element has value more than 9

[False False False False False False False False False  True]


In [16]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 9
np_array[my_mask]
# show me only the elements that are True (fulfilling the mask) 

array([10])

In [17]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array >= 9
np_array[my_mask]
# show me only the elements that are True (fulfilling the mask)

# only True subset can be seen (the fulfilling and worthy)

array([ 9, 10])

In [55]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array == 9
np_array[my_mask]
# show me only the elements that are True (fulfilling the mask)

# only True subset can be seen (the fulfilling and worthy)

array([9])

In [56]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array = 9
np_array[my_mask]
# show me only the elements that are True (fulfilling the mask)

# only True subset can be seen (the fulfilling and worthy)

# Fulfilling the requirement of the mask involves a question
# being asked - e.g. == and not =

TypeError: 'int' object is not subscriptable

In [18]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

np_array[~(np_array > 3)] # means NOT more than 3!


array([1, 2, 3])

In [19]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np_array[(np_array > 3) & (np_array < 8)] # interval!
# more than 3 and less than 8


array([4, 5, 6, 7])

In [20]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np_array[(np_array < 3) | (np_array > 8)] # the vertical line means
# OR


array([ 1,  2,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [21]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[3] # What are the elements with the third index
 # 4th place

[4, 'D']

In [22]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[3][0] # What are the elements with the third index
 # 4th place

4

In [23]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[3][1] # What are the elements with the third index
 # 4th place only the SECOND one within the list

'D'

In [24]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[0][0] # What are the elements with the first index
 # 1st place only the FIRST one within the list

1

In [25]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[0][1] # What are the elements with the first index
 # 1st place-  only the SECOND one within that list

'A'

In [26]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[:3] # What are the elements with the first index 
# (0th place) to the elements with the second index 
# (2nd place)

[[1, 'A'], [2, 'B'], [3, 'C']]

In [27]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[1:4][0] # What is the first element within the range
# of the elements from the second index
# to the third index 

# Array happens to do better than this

[2, 'B']

In [28]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[1:4][1] # What is the second element within the range
# of the elements from the second index
# to the third index 

# Array happens to do better than this

[3, 'C']

In [29]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[1:4][2] # What is the third element within the range
# of the elements from the second index
# to the third index 

# 1:4 means 1 -> 3 so only indexes 0, 1 and 2 can be applied

[4, 'D']

### 1.4 Indexing & Slicing 2D Arrays

In [30]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

np_array_2d[3] # What is the 4th element (third index)


array(['4', 'D'], dtype='<U11')

In [31]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

np_array_2d[3, 0] # What is the first element (at 0th place) 
# within the 4th element (third index)


'4'

In [32]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

np_array_2d[:4] # indexes 0, 1 , 2  and 3 shown


array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D']], dtype='<U11')

In [33]:
py_list_2d = [[1, "A", 'Z'], [2, "B", 'X'], [3, "C", 'Y'], 
              [4, "D", 'W'], [5, "E", 'V'], [6, "F", 'U'], 
              [7, "G", 'T'], [8, "H", 'S'],
              [9, "I", 'R'], [10, "J", 'Q']]

np_array_2d = np.array(py_list_2d)

np_array_2d[:5, 2] # indexes 0, 1 , 2, 3 and 4 of the major list
# shown index number 2 shown as output
# a list with a list is still a 2D list


array(['Z', 'X', 'Y', 'W', 'V'], dtype='<U11')

In [34]:
py_list_2d = [[1, "A", 'Z'], [2, "B", 'X'], [3, "C", 'Y'], 
              [4, "D", 'W'], [5, "E", 'V'], [6, "F", 'U'], 
              [7, "G", 'T'], [8, "H", 'S'],
              [9, "I", 'R'], [10, "J", 'Q']]

np_array_2d = np.array(py_list_2d)

np_array_2d[3:6, 2] # indexes 3, 4 and 5 of the major list
# shown index number 2 shown as output
# a list with a list is still a 2D list


array(['W', 'V', 'U'], dtype='<U11')

In [35]:
py_list_2d = [[1, "A", 'Z'], [2, "B", 'X'], [3, "C", 'Y'], 
              [4, "D", 'W'], [5, "E", 'V'], [6, "F", 'U'], 
              [7, "G", 'T'], [8, "H", 'S'],
              [9, "I", 'R'], [10, "J", 'Q']]

np_array_2d = np.array(py_list_2d)

np_array_2d[:, 0] # indexes 3, 4 and 5 of the major list
# shown index number 2 shown as output
# a list with a list is still a 2D list


array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

### 1.5 Growing lists

In [36]:
x = [1]*10
x # print() function no need to be typed here


[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [37]:
#Appending one element at a time

x = [1]
x += ['za']
x += ['za']
x

[1, 'za', 'za']

In [38]:
#Appending new elements at one-go 

x = [1]
x += ['za', 'za']
x

[1, 'za', 'za']

In [39]:
# append() function allows appending a list within a list

x = [1]
x.append([2,3,4])
x 

[1, [2, 3, 4]]

In [40]:
# append() function only allows appending elements only one
# at a time

x = [1]
x.append(2)
x 

[1, 2]

In [41]:
# append() function only allows appending elements only one
# at a time

x = [1]
x.append(2, 3, 4)
x 

TypeError: list.append() takes exactly one argument (3 given)

## 2 Some loose ends

### 2.1 Tuples

In [ ]:
a = (1, 2, 3) # define tuple!!

print(a[0]) # first element within the tuple (index = 0)

a[1] # second element within the tuple (index = 1)

In [ ]:
a = (1, 2, 3) # define tuple!!

print(a[0]) # first element within the tuple (index = 0)

a[1] += 10 # cannot add 10 to the second element of the tuple

In [ ]:
a = (1, 2, 3) # define tuple!!

print(a[0]) # first element within the tuple (index = 0)

a[1] = 10 # cannot change the second element of the tuple
# to a new data
# can only happen in list!!!

In [ ]:
a = [1, 2, 3] # define tuple!!

print(a[0]) # first element within the tuple (index = 0)

a[1] = 10 # can change the second element of the list
# to a new data


### 2.2 Be VERY careful when copying

copying lists 
__new list name__ = __old list name__.copy()

***DO NOT*** just use '=' to equate one list to the next list name

## Exercise 1 :  Total recall?



| Term | Brief description |
| :--- |  ---: |
| Subsetting| Wanting certain elements of a list as the output by using their associated index numbers - *for when selecting within list/array*|
| Indexing | Wanting a certain element of a list/array (or even elements of a list within a list) as the output by indicating their associated index number - *selecting just that 1 element* |
| Slicing | Wanting certain elements of a lists/array as the output by using a range made from their assoicated index numbers. Use the index number of the element you want started from and the +1 of the index number of the elememnt you want the output to finish at - *allows selection of this range* |
| Masking | Wanting elements that fulfil a certain requirement **ONLY within arrays** as the output - *only those that are fulfil the 'True' requirement as the output* |




## Exercise 2 :  Show me the ‘odd’ letters

In [2]:
import numpy as np

In [5]:
# EXACTLY WHAT EXERCISE 2 WANTS

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])


# Step 1) Subset all the first elements
ONLY_FIRST_ELEMENTS = np_array_2d[:, 0]

# Step 2) convert the elements
# of the ONLY_FIRST_ELEMENTS into integers, since 
# in first np_arrray_


ONLY_FIRST_ELEMENTS_INTEGERS = ONLY_FIRST_ELEMENTS.astype(int)

# Step 3) Use % to get remainder for its division
# of the integer elements by 2


ONLY_FIRST_ELEMENTS_INTEGERS_REMAINDERS = ONLY_FIRST_ELEMENTS_INTEGERS%2

# Step 4) Filtering to get the mask that checks whether 
# the remainder is 1 (AKA IDENTIFY ODD NUMBER)


FINAL_ARRAY = ONLY_FIRST_ELEMENTS_INTEGERS_REMAINDERS == 1

np_array_2d[FINAL_ARRAY, 1]

# Elements which correspond with the True list

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')

In [50]:
# STEP 1 SUBSETTING ALL THE FIRST ELEMENTS
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

# Array sees the ointeger but automatically converts them 
# into integers

# Step 1) Subset all the first elements

# new array name np_array_2d_ONLY_FIRST_ELEMENTS = 
np_array_2d[:, 0]

# ONLY_FIRST_ELEMENTS = np_array_2d[:, 0]



array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U11')

In [57]:
# STEP 2 CONVERTING ALL THE ELEMENTS IN THE NEW ARRAY
# INTO INTEGERS - THEY WERE PREVIOUSLY STRINGS AS ARRAYS
# CAN ONLY HOLD DATA OF A SINGLE TYPE
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])


# Step 1) Subset all the first elements
ONLY_FIRST_ELEMENTS = np_array_2d[:, 0]

# Step 2) convert the elements
# ONLY_FIRST_ELEMENTS into integers

ONLY_FIRST_ELEMENTS.astype(int)
# ONLY_FIRST_ELEMENTS_INTEGERS = ONLY_FIRST_ELEMENTS.astype(int)


array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [58]:
# STEP 3 GETTING THE REMAINER OF ALL THE DIVISION OF ALL THE 
# ELEMENTS BY 2

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])


# Step 1) Subset all the first elements
np_array_2d_ONLY_FIRST_ELEMENTS = np_array_2d[:, 0]

# Step 2) convert the elements
# of the ONLY_FIRST_ELEMENTS into integers

ONLY_FIRST_ELEMENTS.astype(int)
ONLY_FIRST_ELEMENTS_INTEGERS = ONLY_FIRST_ELEMENTS.astype(int)

# Step 3) Use % to get remainder for its division
# of the integer elements by 2

ONLY_FIRST_ELEMENTS_INTEGERS%2
# ONLY_FIRST_ELEMENTS_INTEGERS_REMAINDERS = ONLY_FIRST_ELEMENTS_INTEGERS%2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int32)

In [60]:
#  STEP 4 CREATING A MASK TO CHECK FOR WHETHER REMAINDER
# IS 0 OR NAH
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])


# Step 1) Subset all the first elements
np_array_2d_ONLY_FIRST_ELEMENTS = np_array_2d[:, 0]

# Step 2) convert the elements
# of the ONLY_FIRST_ELEMENTS into integers

ONLY_FIRST_ELEMENTS.astype(int)
ONLY_FIRST_ELEMENTS_INTEGERS = ONLY_FIRST_ELEMENTS.astype(int)

# Step 3) Use % to get remainder for its division
# of the integer elements by 2

ONLY_FIRST_ELEMENTS_INTEGERS%2
ONLY_FIRST_ELEMENTS_INTEGERS_REMAINDERS = ONLY_FIRST_ELEMENTS_INTEGERS%2

# Step 4) Filtering to get the mask that checks whether 
# the remainder is 1 (AKA IDENTIFY ODD NUMBER)

ONLY_FIRST_ELEMENTS_INTEGERS_REMAINDERS == 1
# FINAL_ARRAY = ONLY_FIRST_ELEMENTS_INTEGERS_REMAINDERS == 1

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [6]:
#  STEP 5 EXTRACTING FROM THE MASK THE CORRESPONDING ELEMENTS
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])


# Step 1) Subset all the first elements
ONLY_FIRST_ELEMENTS = np_array_2d[:, 0]

# Step 2) convert the elements
# of the ONLY_FIRST_ELEMENTS into integers

ONLY_FIRST_ELEMENTS.astype(int)
ONLY_FIRST_ELEMENTS_INTEGERS = ONLY_FIRST_ELEMENTS.astype(int)

# Step 3) Use % to get remainder for its division
# of the integer elements by 2

ONLY_FIRST_ELEMENTS_INTEGERS%2
ONLY_FIRST_ELEMENTS_INTEGERS_REMAINDERS = ONLY_FIRST_ELEMENTS_INTEGERS%2

# Step 4) Filtering to get the mask that checks whether 
# the remainder is 1 (AKA IDENTIFY ODD NUMBER)

ONLY_FIRST_ELEMENTS_INTEGERS_REMAINDERS == 1
FINAL_ARRAY = ONLY_FIRST_ELEMENTS_INTEGERS_REMAINDERS == 1

np_array_2d[FINAL_ARRAY, 1] # First element of each array element correspond

# Elements which correspond with the True list

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')

In [3]:
#  STEP 5 EXTRACTING FROM THE MASK THE CORRESPONDING ELEMENTS
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])


# Step 1) Subset all the first elements
ONLY_FIRST_ELEMENTS = np_array_2d[:, 0]

# Step 2) convert the elements
# of the ONLY_FIRST_ELEMENTS into integers

ONLY_FIRST_ELEMENTS.astype(int)
ONLY_FIRST_ELEMENTS_INTEGERS = ONLY_FIRST_ELEMENTS.astype(int)

# Step 3) Use % to get remainder for its division
# of the integer elements by 2

ONLY_FIRST_ELEMENTS_INTEGERS%2
ONLY_FIRST_ELEMENTS_INTEGERS_REMAINDERS = ONLY_FIRST_ELEMENTS_INTEGERS%2

# Step 4) Filtering to get the mask that checks whether 
# the remainder is 1 (AKA IDENTIFY ODD NUMBER)

ONLY_FIRST_ELEMENTS_INTEGERS_REMAINDERS == 1
FINAL_ARRAY = ONLY_FIRST_ELEMENTS_INTEGERS_REMAINDERS == 1

np_array_2d[FINAL_ARRAY] # 

# Elements which correspond with the True list, but both

array([['1', 'A'],
       ['3', 'C'],
       ['5', 'E'],
       ['7', 'G'],
       ['9', 'I']], dtype='<U11')

In [2]:
import numpy as np
#  STEP 5 EXTRACTING FROM THE MASK THE CORRESPONDING ELEMENTS
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])


# Step 1) Subset all the first elements
ONLY_FIRST_ELEMENTS = np_array_2d[:, 0]

# Step 2) convert the elements
# of the ONLY_FIRST_ELEMENTS into integers

ONLY_FIRST_ELEMENTS.astype(int)
ONLY_FIRST_ELEMENTS_INTEGERS = ONLY_FIRST_ELEMENTS.astype(int)

# Step 3) Use % to get remainder for its division
# of the integer elements by 2

ONLY_FIRST_ELEMENTS_INTEGERS%2
ONLY_FIRST_ELEMENTS_INTEGERS_REMAINDERS = ONLY_FIRST_ELEMENTS_INTEGERS%2

# Step 4) Filtering to get the mask that checks whether 
# the remainder is 1 (AKA IDENTIFY ODD NUMBER)

ONLY_FIRST_ELEMENTS_INTEGERS_REMAINDERS == 1
FINAL_ARRAY = ONLY_FIRST_ELEMENTS_INTEGERS_REMAINDERS == 1

FINAL_ARRAY

# Elements which correspond with the True list

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

**HOW DID THE ABOVE WORK? :(** - THE FINAL STEP - FINAL_ARRAY is True and False array, translates to 1 and 0 respectively.