<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Random Numbers (Need)</span></div>

## 1 Random Numbers

### 1.1 Real and Pseudo Random Numbers

### 1.2 NumPy’s PRNG

In [7]:
import numpy as np


In [2]:
np.random.rand() # give just one

0.49882412255484876

In [3]:
np.random.rand(10) # 10 random numbers in 1 array

array([0.6090514 , 0.6709942 , 0.09737853, 0.20952038, 0.66779638,
       0.68401801, 0.91411664, 0.93408432, 0.62163208, 0.597649  ])

In [4]:
np.random.choice(5) # something from 0 to 5, gives a list

3

In [5]:
np.random.randint(10) # integer from 0 to 10

6

In [6]:
np.random.rand(5,2) # give 5 sets of 2 random numbers

array([[0.1359542 , 0.87923868],
       [0.02530824, 0.20834673],
       [0.54357962, 0.53536974],
       [0.86759377, 0.69543767],
       [0.19599108, 0.76195541]])

In [7]:
np.random.rand(10,2,4) # 10 lists of 2 lists of 4 random numbers

# all numbers between 0 and 1

# unifrom distribution within the list

array([[[0.72883   , 0.97781442, 0.49087613, 0.98744016],
        [0.83620853, 0.27071807, 0.68937666, 0.62878668]],

       [[0.85351322, 0.13984861, 0.19762389, 0.23426086],
        [0.54434433, 0.07920905, 0.61924235, 0.33533517]],

       [[0.4960372 , 0.68332402, 0.29690691, 0.71948493],
        [0.52926519, 0.18640715, 0.60263156, 0.80588996]],

       [[0.80363419, 0.01309329, 0.32762829, 0.42919787],
        [0.94800247, 0.98670945, 0.39132988, 0.68678381]],

       [[0.08501122, 0.79469709, 0.00390533, 0.84285396],
        [0.14419283, 0.44808032, 0.05324614, 0.32496133]],

       [[0.24820998, 0.94782893, 0.50023125, 0.12121891],
        [0.06162459, 0.83848918, 0.5528756 , 0.36314339]],

       [[0.86239725, 0.06970855, 0.59999065, 0.9179631 ],
        [0.11897219, 0.90619486, 0.82541502, 0.74886479]],

       [[0.35996004, 0.14089295, 0.9990223 , 0.50947056],
        [0.19087551, 0.66858552, 0.7423631 , 0.30560578]],

       [[0.76711808, 0.46248648, 0.44486989, 0.69402408]

In [8]:
random_number = []
random_number += [np.random.choice(10)]

number_list = [1,2,3,4,5,6,7,8,9,10]


if random_number == number_list.any():
    print('random number is in number_list')

AttributeError: 'list' object has no attribute 'any'

In [ ]:
n = 10000
random_numbers = np.random.rand(n)

# The numbers less than .5 must be about 50%
print(np.sum(random_numbers < .5)/n*100)

# The numbers less than .25 must be about 25%
print(np.sum(random_numbers < .25)/n*100)

# The numbers more than .75 must be about 25%
np.sum(random_numbers > .75)/n*100

In [ ]:
import numpy as np
import os
import glob
import shutil
import math
from matplotlib import pyplot as plt

### 1.3 A simple graphical test

In [ ]:
# Plot numbers as scatter plot

n = 10000
random_numbers = np.random.rand(n)

fig, ax = plt.subplots(nrows = 2, ncols = 1)

axis = ax[0]
axis.hist(random_numbers, bins = 100, alpha = .25)
axis.set_xlabel('Value of random number')
axis.set_ylabel('Frequency')

axis = ax[1]
axis.scatter(range(n), random_numbers, alpha = .25)
axis.set_xlabel('Position in the random number list')
axis.set_ylabel('Value of random number')

plt.show()

### 1.4 Uniformly beyond \([0,1)\)

In [ ]:
n = 10000
random_numbers = np.random.uniform(low = 50, high = 100, size = n)
# interval [50, 100]

fig, ax = plt.subplots(nrows = 2, ncols = 1)

axis = ax[0]
axis.hist(random_numbers, bins = 100, alpha = .25)
axis.set_xlabel('Value of random number')
axis.set_ylabel('Frequency')

axis = ax[1]
axis.scatter(range(n), random_numbers, alpha = .25)
axis.set_xlabel('Position in the random number list')
axis.set_ylabel('Value of random number')

plt.show()

### 1.5 ‘seeding’ a PRNG

In [ ]:
np.random.randint(0, 100, 10)

In [ ]:
n = 10
np.random.rand(0, 100, n)

In [ ]:
np.random.seed(1234) # Specifying a seed
np.random.randint(0, 100, 10) # Ten integers between 0 and 100

In [ ]:
np.random.seed(1234)
np.random.randint(0, 100, 10)

In [ ]:
np.random.seed(12)
np.random.randint(0, 100, 10)

In [ ]:
np.random.seed(12)
np.random.randint(0, 100, 10) # test if it come out the same

In [ ]:
np.random.seed(1)
np.random.randint(0, 200, 10)

In [ ]:
np.random.seed(1)
np.random.randint(0, 200, 10) # test if it come out the same

## 2 Simulating a Magic-8 Ball

## 3 Flipping Coins

### 3.1 A fair coin

In [ ]:
def shake_magic_8():
    
    # Function to simulate a Magic-8 ball
    
    options = ['It is certain.', 'It is decidedly so.', 'Without a doubt.', 'Yes definitely.'
              , 'You may rely on it.', 'As I see it, yes.', 'Most likely.', 'Outlook good.',
              'Yes.', 'Signs point to yes.', 'Reply hazy, try again.', 'Ask again later.',
              'Btter not tell you now.', 'Cannot predict now.', 'Concentrate and ask again.',
              'Don\'t count on it', 'My reply is no.', 'My sources say no.', 'Outlook not so good',
              'Very doubtful.']
    
    return np.random.choice(options)

questions = ['Will I be pretty?', 'Will I be rich?', 'Will I be in trouble?']

for question in questions:
    print(f'Q: {question}')
    print(f'A: {shake_magic_8()}\n') # \n means enter a new line on the output

### 3.2 A biased coin

In [ ]:
np.random.choice(['Heads', 'Tails'])

In [ ]:
np.random.choice(10)

In [ ]:
no_of_coins = 10
np.random.choice(['Head', 'Tails'], no_of_coins)

In [ ]:
np.random.choice(['Head', 'Tails'], 20)

In [ ]:
np.random.choice([90,110], 20)

In [ ]:
np.random.randint(90, 110, 9)

In [ ]:
def flip_coins(no_of_coins = 1, probability = .5):
    # Returns the number of values greater than 'probability' (considered as 'Heads')
    results = np.random.rand(no_of_coins)
    no_of_heads = np.sum(results > probability)
    return no_of_heads

no_of_coins = 1_000
no_of_heads = flip_coins(no_of_coins)
print(f'Number of heads: {no_of_heads/no_of_coins*100:.2f}%')

In [ ]:
no_of_coins = 1000
no_of_heads = flip_coins(no_of_coins, probability = .3)
print(f'Number of heads: {no_of_heads/no_of_coins*100:.2f}%')

### 3.3 A flipping experiment

In [ ]:
from matplotlib import rcParams

In [ ]:
no_of_repeats = 10_000
result = [flip_coins(no_of_coins = 10) for _ in range(no_of_repeats)]
no_of_heads, head_counts = np.unique(result, return_counts = True) # returns unique values (of Heads) in the list and how
                                                                    # many times they occur
    
heads_probability = head_counts / no_of_repeats # get probabilities by dividing the array with the counts by the number
                                                # of repeats

plt.rcParams['figure.figsize'] = (10,5)
plt.bar(no_of_heads, head_counts)
plt.xlabel('No of heads')
plt.ylabel(f'Frequency out of {no_of_repeats}')
plt.table([no_of_heads, head_counts, heads_probability], rowlabels = ['No of Heads', 'Frequency', 'PRNG Probability'],
          loc = 'bottom', bbox = [0, -0.5, 1, 0.3]) # HELP

plt.show()

In [ ]:
pip install scipy

In [ ]:
from scipy.stats import binom # machinery for binomial distribution

In [ ]:
binom.pmf(k = 7, n = 10, p = .5)

In [ ]:
binomial_probabilities = binom.pmf(k = no_of_heads, n = 10, p = .5)

no_of_repeats = 10_000
result = [flip_coins(no_of_coins = 10) for _ in range(no_of_repeats)]
no_of_heads, head_counts = np.unique(result, return_counts = True) # returns unique values (of Heads) in the list and how
                                                                    # many times they occur
    
heads_probability = head_counts / no_of_repeats # get probabilities by dividing the array with the counts by the number
                                                # of repeats

plt.rcParams['figure.figsize'] = (10,5)
plt.bar(no_of_heads, head_counts)
plt.xlabel('No of heads')
plt.ylabel(f'Frequency out of {no_of_repeats}')
plt.table([no_of_heads, head_counts, heads_probability], rowlabels = ['No of Heads', 'Frequency', 'PRNG Probability'],
          loc = 'bottom', bbox = [0, -0.5, 1, 0.3]) # HELP

plt.show()

## Exercise 1 :  12C, 13C

In [ ]:
np.random.choice(['12C', '13C'], 27)

# Finding 13C with 13C

In [10]:
import numpy as np

In [37]:
# EXACTLY WHAT THEY WANT 1. mean and standard deviation for the number of 13C atoms in a C27H44O atom

# np.random.choice(['12C', '13C'])
def C_chances(no_of_C_atoms = 27, probability = .9889):
    
    results = np.random.rand(no_of_C_atoms)
    no_of_13C_atoms = np.sum(results > probability)
    return no_of_13C_atoms
    print(no_of_13C_atoms)

# no_of_C_atoms = 27
# no_of_13C_atoms = C_chances(no_of_C_atoms)

# mean = (no_of_13C_atoms/no_of_C_atoms) # is as a %
# mean

no_of_repeats = 10_000
result = [C_chances(no_of_C_atoms = 27) for _ in range(no_of_repeats)] # 10_000 cholesterol molecules - 13C atoms
no_of_13C_atoms, total_number_of_C_atoms = np.unique(result, return_counts = True)
print(no_of_13C_atoms) # the UNIQUE values (just what each element can be)
print(total_number_of_C_atoms) # number of times each unique element shows up
print(np.mean(result)) # Mean of 13C atoms
np.std(result) # Standard deviation of 
# print(no_of_13C_atoms/total_number_of_C_atoms)

[0 1 2 3 4]
[7429 2225  320   24    2]
0.2945


0.5371868855435694

In [33]:
# EXACTLY WHAT THEY WANT

probability_no_13C = 7401/10_000
probability_no_13C

0.7401

In [3]:
# 1. mean and standard deviation for the number of 13C atoms in a C27H44O atom

# np.random.choice(['12C', '13C'])
def C_chances(no_of_C_atoms = 27, probability = .9889):
    
    results = np.random.rand(no_of_C_atoms)
    no_of_13C_atoms = np.sum(results > probability)
    return no_of_13C_atoms

no_of_C_atoms = 27
no_of_13C_atoms = C_chances(no_of_C_atoms)

mean = (no_of_13C_atoms/no_of_C_atoms)*100 # is as a %
mean

NameError: name 'np' is not defined

In [14]:
# 1. mean and standard deviation for the number of 13C atoms in a C27H44O atom

# np.random.choice(['12C', '13C'])
def C_chances(no_of_C_atoms = 27, probability = .9889):
    
    results = np.random.rand(no_of_C_atoms)
    no_of_13C_atoms = np.sum(results > probability)
    return no_of_13C_atoms

no_of_C_atoms = 27
no_of_13C_atoms = C_chances(no_of_C_atoms)

mean = (no_of_13C_atoms/no_of_C_atoms)*100 # is as a %
mean

3.7037037037037033

In [20]:
# 1. mean and standard deviation for the number of 13C atoms in a C27H44O atom

# np.random.choice(['12C', '13C'])
def C_chances(no_of_C_atoms = 27, probability = .9889):
    
    results = np.random.rand(no_of_C_atoms)
    no_of_13C_atoms = np.sum(results > probability)
    return no_of_13C_atoms

no_of_C_atoms = 27
no_of_13C_atoms = C_chances(no_of_C_atoms)

print(f'mean of 13C atoms: {no_of_13C_atoms/no_of_C_atoms*100:.20f}%') 


mean of 13C atoms: 3.70370370370370327606%


# Finding 13C mean with 12C 

In [49]:
# np.random.choice(['12C', '13C'])
def C_chances(no_of_C_atoms = 27, probability = .9889):
    
    results = np.random.rand(no_of_C_atoms)
    no_of_12C_atoms = np.sum(results < probability)
    return no_of_12C_atoms

no_of_C_atoms = 27
no_of_12C_atoms = C_chances(no_of_C_atoms)

mean_of_12C_atoms = (no_of_12C_atoms/no_of_C_atoms)*100

mean_of_13C_atoms = 100 - mean_of_12C_atoms
mean_of_13C_atoms

3.7037037037037095

In [54]:
# np.random.choice(['12C', '13C'])
def C_chances(no_of_C_atoms = 27, probability = .9889):
    
    results = np.random.rand(no_of_C_atoms)
    no_of_12C_atoms = np.sum(results < probability)
    return no_of_12C_atoms

no_of_C_atoms = 27
no_of_12C_atoms = C_chances(no_of_C_atoms)

mean_of_12C_atoms = (no_of_12C_atoms/no_of_C_atoms)

mean_of_13C_atoms = 100 - mean_of_12C_atoms
mean_of_13C_atoms

11.111111111111114

In [62]:
# np.random.choice(['12C', '13C'])
def C_chances(no_of_C_atoms = 27, probability = .9889):
    
    results = np.random.rand(no_of_C_atoms)
    no_of_12C_atoms = np.sum(results < probability)
    return no_of_12C_atoms

no_of_C_atoms = 27
no_of_12C_atoms = C_chances(no_of_C_atoms)

mean_of_12C_atoms = (no_of_12C_atoms/no_of_C_atoms)*100

mean_of_13C_atoms = 100 - mean_of_12C_atoms
mean_of_13C_atoms

11.111111111111114

In [62]:
# np.random.choice(['12C', '13C'])
def C_chances(no_of_C_atoms = 27, probability = .9889):
    
    results = np.random.rand(no_of_C_atoms)
    no_of_12C_atoms = np.sum(results < probability)
    return no_of_12C_atoms

no_of_C_atoms = 27
no_of_12C_atoms = C_chances(no_of_C_atoms)

mean_of_12C_atoms = (no_of_12C_atoms/no_of_C_atoms)*100

mean_of_13C_atoms = 100 - mean_of_12C_atoms
mean_of_13C_atoms

11.111111111111114

# Finding 13C Standard Deviation with 13C

In [65]:
# 1. mean and standard deviation for the number of 13C atoms in a C27H44O atom

# np.random.choice(['12C', '13C'])
def C_chances(no_of_C_atoms = 27, probability = .9889):
    # Returns the number of values greater than 'probability' (considered as 'Heads')
    results = np.random.rand(no_of_C_atoms)
    return results
    no_of_13C_atoms = np.sum(results > probability)
    return no_of_13C_atoms

no_of_C_atoms = 27
no_of_13C_atoms = C_chances(no_of_C_atoms)


print(f'mean of 13C atoms: {no_of_13C_atoms/no_of_C_atoms*100:.20f}%') #HELP



TypeError: unsupported format string passed to numpy.ndarray.__format__

In [73]:
def C_chances(no_of_C_atoms = 27, probability = .9889):
    
    results = np.random.rand(no_of_C_atoms)
    no_of_13C_atoms = np.sum(results > probability)
    return no_of_13C_atoms

no_of_C_atoms = 27
no_of_13C_atoms = C_chances(no_of_C_atoms)

print(no_of_13C_atoms)
mean = (no_of_13C_atoms/no_of_C_atoms)*100 
mean

2


7.4074074074074066

In [74]:
numerator = (no_of_13C_atoms - mean)**2

denominator = no_of_C_atoms

std = np.sqrt(numerator/denominator)



In [75]:
std

1.0406560407615475

In [103]:
# The final code

def C_chances(no_of_C_atoms = 27, probability = .9889):
    
    results = np.random.rand(no_of_C_atoms)
    no_of_13C_atoms = np.sum(results > probability)
    return no_of_13C_atoms

no_of_C_atoms = 27
no_of_13C_atoms = C_chances(no_of_C_atoms)

print(no_of_13C_atoms)
mean = (no_of_13C_atoms/no_of_C_atoms)
print(mean)

# STD
numerator = (no_of_13C_atoms - mean)**2
denominator = no_of_C_atoms
std = np.sqrt(numerator/denominator)
print(std)

1
0.037037037037037035
0.18532230862876875


In [104]:
def C_chances(no_of_C_atoms = 27, probability = .9889):
    
    results = np.random.rand(no_of_C_atoms)
    no_of_13C_atoms = np.sum(results > probability)
    return no_of_13C_atoms

no_of_C_atoms = 27
no_of_13C_atoms = C_chances(no_of_C_atoms)

print(no_of_13C_atoms)
mean = (no_of_13C_atoms/no_of_C_atoms)
print(mean)

# STD
numerator = (no_of_13C_atoms - mean)**2
denominator = no_of_C_atoms
std = np.sqrt(numerator/denominator)
print(std)

0
0.0
0.0


In [167]:
def C_chances(no_of_C_atoms = 27, probability = .9889):
    
    results = np.random.rand(no_of_C_atoms)
    no_of_13C_atoms = np.sum(results > probability)
    return no_of_13C_atoms

no_of_C_atoms = 27
no_of_13C_atoms = C_chances(no_of_C_atoms)

print(no_of_13C_atoms)
mean = (no_of_13C_atoms/no_of_C_atoms)
print(mean)

# STD
numerator = (no_of_13C_atoms - mean)**2
denominator = no_of_C_atoms
std = np.sqrt(numerator/denominator)
print(std)

1
0.037037037037037035
0.18532230862876875


In [167]:
def C_chances(no_of_C_atoms = 27, probability = .9889):
    
    results = np.random.rand(no_of_C_atoms)
    no_of_13C_atoms = np.sum(results > probability)
    return no_of_13C_atoms

no_of_C_atoms = 27
no_of_13C_atoms = C_chances(no_of_C_atoms)

print(no_of_13C_atoms)
mean = (no_of_13C_atoms/no_of_C_atoms)
print(mean)

# STD
numerator = (no_of_13C_atoms - mean)**2
denominator = no_of_C_atoms
std = np.sqrt(numerator/denominator)
print(std)

1
0.037037037037037035
0.18532230862876875


# The probability that there are no 13C atoms in a molecule of C27H44O

In [182]:
# np.random.choice(['12C', '13C'])
def C_chances(no_of_C_atoms = 27, probability = .9889):
    
    results = np.random.rand(no_of_C_atoms)
    no_of_12C_atoms = np.sum(results < probability)
    return no_of_12C_atoms

no_of_C_atoms = 27
no_of_12C_atoms = C_chances(no_of_C_atoms)
print(no_of_12C_atoms)

mean_of_12C_atoms = (no_of_12C_atoms/no_of_C_atoms)
mean_of_12C_atoms

26


0.9629629629629629

# Try to get their answer

In [200]:
def C_chances(no_of_C_atoms = 27, probability = .9889):
    
    results = np.random.rand(no_of_C_atoms)
    no_of_13C_atoms = np.sum(results > probability)
    return no_of_13C_atoms

no_of_C_atoms = 27
no_of_repeats = 10_000
result = [C_chances(no_of_C_atoms = 27) for _ in range(no_of_repeats)]
no_of_13C, C_atom_counts = np.unique(result, return_counts = True)

print(no_of_13C)

print(C_atom_counts)

[0 1 2 3 4]
[7339 2304  322   34    1]


In [203]:
def C_chances(no_of_C_atoms = 27, probability = .9889):
    
    results = np.random.rand(no_of_C_atoms)
    no_of_13C_atoms = np.sum(results > probability)
    return no_of_13C_atoms

no_of_repeats = 10
result = [C_chances(no_of_C_atoms = 27) for _ in range(no_of_repeats)]
no_of_13C, C_count = np.unique(result, return_counts = True) # returns unique values (of 13C) in the list and how
                                                                    # many times they occur
    
C13_probability = C_count / no_of_repeats
C13_probability # HELP

array([0.4, 0.6])